### ISSUE TITLE
Feature request: option to allow non-existing .env file

### ISSUE THREAD

**Issue by kretz** [grimen/node-env-file#11]
I use a .env file for development, but not for production (where I set the environment variables through AWS mechanisms). 

So my problem is that I need to wrap my code in production to detect a missing .env file. I'd rather just have noting happen if the .env file was not there.

I can do the changes and send a PR. Is it a feature that would be accepted?

Thanks,
Martin

**Comment by grimen** [comment]
Sure, there could be a flag that tells if it should throw an exception or not.

**Comment by grimen** [comment]
I realized this was already there but not documented or tested. Adding specs for it now while I am onto other bugs anyway. Reference: https://github.com/grimen/node-env-file/blob/master/lib/index.js#L28-L34

**Comment by grimen** [comment]
Added a note on `raise` option: https://github.com/grimen/node-env-file/commit/dd83460f435d5d4c5feae0d33d48e4d08640531c

Closing this as it is supported.
