### ISSUE TITLE
possible regression of V0.1.6 vs v0.1.5

### ISSUE THREAD

**Issue by maldestor95** [grimen/node-env-file#13]
Hi grimen,

I have just found a possible regression of node-env-file v0.1.6 vs v0.1.5;
Please find below what I found out.

Can you confirm the issue?

Thanks,
 Maldestor95

#  code for 

## App.js

```
var env = require('node-env-file');
console.log('***');
try{
    env('process.env',{verbose: true, overwrite: true});
    console.log('***processed***');
    console.log ('NODE_ENV='+process.env.NODE_ENV);
    console.log(process.env.NODE_ENV);

}
catch (e) {
    console.log("ERROR "+e);
}
```

## process.env
```
NODE_ENV=development
OTHER_ENV=FOO
```

# Console output
## "node-env-file": "0.1.5"
![image](https://cloud.githubusercontent.com/assets/9538454/6230199/06e727da-b6be-11e4-974c-42f7da66fbb7.png)

## "node-env-file": "0.1.6"
![image](https://cloud.githubusercontent.com/assets/9538454/6230196/021f0f38-b6be-11e4-943b-b5d66ba8ed1f.png)

**Comment by grimen** [comment]
Thanks for the bug report, I will look at it now.

**Comment by grimen** [comment]
I could not reproduce the error. I think it could be related to Windows environments only, could you help me figure out what row the error is raised on? I don't got any Windows environment.

![](https://www.evernote.com/shard/s3/sh/eaa90f87-ef54-4c38-9321-f8065277c4fe/d88e49eefadb05ae38bf38a6224b1868/res/e05cf896-0bf3-4987-84f0-eacece24e388/skitch.png?resizeSmall&width=832)

**Comment by maldestor95** [comment]
I have clone the repository on my computer; 

This is what I got:

![image](https://cloud.githubusercontent.com/assets/9538454/6239695/7e791f36-b706-11e4-960c-e182b6481355.png)


Now I run the examples/basic.js test

![image](https://cloud.githubusercontent.com/assets/9538454/6239703/92ef5142-b706-11e4-8442-83ea9feb3953.png)
It looks like I the error is on line 104 on lib/index.js

![image](https://cloud.githubusercontent.com/assets/9538454/6239712/aa1f0650-b706-11e4-80ef-48fcffd66516.png)

while it's working fine on v0.1.5


after investigation on the file, I find out that the issue concerns the carriage returns character ```\r```:
If I removed the last char like this: (see around line 104)
```
                module.exports.lines.variables.push(line)
                console.log('Line *' +line+'*');
                line = line.substring(0, line.length - 1);
                console.log('Line without \r *'+line+'*')
                var key_value = line.match(/^([^=]+)\s*=\s*(.*)$/)
                console.log('key_value *'+key_value+'*');
                var env_key = key_value[1]
```
It works nicely. It would be better to work on the regex to avoid the use of the substring function but I didn't find a way round it


Here is the output I got from adding the console into the code
![image](https://cloud.githubusercontent.com/assets/9538454/6240220/02131c66-b70c-11e4-9602-4d7fc55f5415.png)

**Comment by grimen** [comment]
@maldestor95  Thanks, this is very helpful. Managed to trigger a failed test for this: 

![](https://www.evernote.com/shard/s3/sh/62e26b10-426f-42c0-8edf-dacfaf1e371b/976dbbf2c89067fa513b8a8b0d4a47a0/res/d8647f71-cb1c-4417-bc14-9283ae7841ef/skitch.png?resizeSmall&width=832)

Need to figure out a clean way to test this now without bloat.

**Comment by grimen** [comment]
Generated some failing tests and fixed the issue, give it a try. Thanks for the visual details!

**Comment by maldestor95** [comment]
@grimen,

 Just to let you know I have successfully tested 0.1.7 on windows 8.1.
* inside the clone copy of the repo
* used as a dependency of my app.

Thanks for the quick fix

**Comment by grimen** [comment]
Great!
