### ISSUE TITLE
fs.existsSync(path) is deprecated

### ISSUE THREAD

**Issue by raghuveer-s** [grimen/node-env-file#17]
According to the latest docs, https://nodejs.org/api/fs.html#fs_fs_existssync_path is deprecated. It recommends changing it to either fs.statSync(path) or fs.accessSync().

**Comment by grimen** [comment]
OK, thank you for reminder. I will fix it as soon as got sparetime.

**Comment by lettertwo** [comment]
FYI, this is no longer the case! 🤣 

Docs currently state:

> Note that fs.exists() is deprecated, but fs.existsSync() is not.
