### ISSUE TITLE
can't set false !

### ISSUE THREAD

**Issue by andrewlorenz** [grimen/node-env-file#20]
Given a file containing

RESPOND_TO_EDITED=false

process.env.RESPOND_TO_EDITED is set to 'false'

which is literally 'false', but unfortunately truthy ...

**Comment by grimen** [comment]
Yes, this is where the **related** library `node-env-flag` comes in:

https://github.com/grimen/node-env-flag

It is not happening automatically because the original philosophy was to only implement bare minimum.
